version: '3'

services:
  nginx:
    image: nginx:1.21.6
    container_name: webserver
    restart: on-failure
    ports:
      - 8080:80
      - 443:443
    volumes:
     - ./www:/var/www
     - ./conf.d:/etc/nginx/conf.d
     - ./conf/nginx.conf:/etc/nginx/nginx.conf